- name: Install nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: Enable nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Configure sites
  ansible.builtin.template:
    src: site.conf.j2
    dest: /etc/nginx/conf.d/site.conf
    mode: "0644"
  notify: Reload nginx

