---
common_base_packages:
  - curl
  - git
  - tar
  - unzip
  - vim
  - wget
  - chrony

env_common_extra_packages: []
env_node_exporter_enabled: true
env_node_exporter_version: "1.8.1"
env_app_user: app
env_app_group: app
env_log_dir: /var/log/apps
env_timezone: UTC
