---
name: Lint Ansible
on:
  push:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install tools
        run: |
          pip install ansible-core ansible-lint yamllint
      - name: yamllint
        run: yamllint ./infra/terraform/gcp/
      - name: ansible-lint
        run: ansible-lint
